### ISSUE TITLE
Compatibility with s3

### ISSUE THREAD

**Issue by timersys** [spatie/laravel-image-optimizer#59]
I was introduced to this library by froala nova field https://github.com/froala/nova-froala-field but I found that is not working with s3. 
We use s3 to store images to save the hassle of using a nfs as we are behind a node balancer.

The exact error I have is : 
```
[2018-12-05 09:41:27] local.ERROR: `Screenshot_6.png` does not exist {"userId":1,"email":"damian@timersys.com","exception":"[object] (InvalidArgumentException(code: 0): `Screenshot_6.png` does not exist at /shared/repos/Repos/geotapi/vendor/spatie/image-optimizer/src/Image.php:14)
[stacktrace]
#0 /shared/repos/Repos/geotapi/vendor/spatie/image-optimizer/src/OptimizerChain.php(72): Spatie\\ImageOptimizer\\Image->__construct('Screenshot_6.pn...')
#1 /shared/repos/Repos/geotapi/vendor/froala/nova-froala-field/src/Handlers/StorePendingAttachment.php(87): Spatie\\ImageOptimizer\\OptimizerChain->optimize('Screenshot_6.pn...')
#2 /shared/repos/Repos/geotapi/vendor/froala/nova-froala-field/src/Handlers/StorePendingAttachment.php(53): Froala\\NovaFroalaField\\Handlers\\StorePendingAttachment->imageOptimize('Screenshot_6.pn...')
#3 [internal function]: Froala\\NovaFroalaField\\Handlers\\StorePendingAttachment->__invoke(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
```

**Comment by freekmurze** [comment]
This package can only optimize local images.
